"""Regenerate openosint/graph/ftm_prop_types.py from the installed followthemoney.

Run with the `graph` extra installed:  python scripts/gen_ftm_prop_types.py
tests/test_ftm_compat_parity.py fails if the committed table drifts from the model.
"""

from __future__ import annotations

from pathlib import Path

from followthemoney import model

from openosint.graph.ftm_compat import VENDORED_SCHEMAS

OUT = Path(__file__).resolve().parent.parent / "openosint" / "graph" / "ftm_prop_types.py"

HEADER = '''"""GENERATED by scripts/gen_ftm_prop_types.py — do not edit by hand.

FollowTheMoney property types for the schemas OpenOSINT emits, so the graph
store works without followthemoney (and therefore without PyICU's native
build). tests/test_ftm_compat_parity.py checks this against the real model.
"""

PROP_TYPES: dict[str, dict[str, str]] = {
'''


def main() -> None:
    lines = [HEADER]
    for name in sorted(VENDORED_SCHEMAS):
        schema = model.get(name)
        lines.append(f"    {name!r}: {{\n")
        for prop in sorted(schema.properties):
            lines.append(f"        {prop!r}: {schema.get(prop).type.name!r},\n")
        lines.append("    },\n")
    lines.append("}\n")
    OUT.write_text("".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
